name: Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Deploy Docker Image
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.4.0
      - name: Build and push
        uses: openzim/docker-publish-action@v10
        with:
          image-name: openzim/zimit-ui
          on-master: latest
          restrict-to: openzim/zimit-frontend
          registries: ghcr.io
          credentials:
            GHCRIO_USERNAME=${{ secrets.GHCR_USERNAME }}
            GHCRIO_TOKEN=${{ secrets.GHCR_TOKEN }}
