name: QA

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check-qa:
    runs-on: ubuntu-latest

    steps:
    - name: Retrieve source code
      uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r api/requirements.txt

    - name: black code formatting check
      run: |
        pip install -U "black==22.3.0"
        black --check .
